"""Report writing tool (markdown files under workspace/reports)."""
import re
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from ..base import Risk, ToolContext, ToolError, ToolRegistry


class WriteReportParams(BaseModel):
    title: str = Field(..., min_length=1, description="Report title (used as heading and file name).")
    content_markdown: str = Field(..., min_length=1, description="Report body in Markdown (sections, tables, bullets).")
    filename: Optional[str] = Field(None, description="Optional file name (without directories); defaults to a slug of the title.")
    overwrite: bool = Field(False, description="Replace an existing report with the same name (needs approval).")


def _slugify(text: str) -> str:
    slug = re.sub(r"[^\w\u0600-\u06FF]+", "-", text, flags=re.UNICODE).strip("-").lower()
    return slug[:80] or "report"


def _target(params: WriteReportParams, ctx: ToolContext):
    name = params.filename or f"{_slugify(params.title)}.md"
    name = name.replace("/", "-").replace("\\", "-")
    if not name.endswith(".md"):
        name += ".md"
    return ctx.resolve_path(f"reports/{name}")


def _report_risk(params: BaseModel, ctx: ToolContext) -> Risk:
    assert isinstance(params, WriteReportParams)
    try:
        return "confirm" if _target(params, ctx).exists() else "safe"
    except ToolError:
        return "safe"


def register(registry: ToolRegistry) -> None:
    @registry.tool("write_report", "Save a Markdown report into workspace/reports/. Overwriting an existing report requires approval.",
                   WriteReportParams, risk_fn=_report_risk, tags=["reports", "write"])
    def write_report(params: WriteReportParams, ctx: ToolContext):
        target = _target(params, ctx)
        if target.exists() and not params.overwrite:
            raise ToolError(f"report '{ctx.display_path(target)}' exists; set overwrite=true (needs approval) or choose another filename")
        target.parent.mkdir(parents=True, exist_ok=True)
        body = params.content_markdown.strip()
        if not body.lstrip().startswith("#"):
            body = f"# {params.title}\n\n{body}"
        stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        body += f"\n\n---\n_Generated by Nimna agent on {stamp}_\n"
        target.write_text(body, encoding="utf-8")
        return {"report": ctx.display_path(target), "chars": len(body)}
